name: Deploy
on:
    push:
        branches:
            - 'master'

jobs:
    build:
        name: Deploy code to test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Deploy
              uses: musps/action-deployer-php@master
              with:
                  args: deploy test -f /home/deploy/api/deploy.php
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
